#!/usr/bin/python2.6
# -*- coding: utf-8 -*-

# This file is a part of Metagam project.
#
# Metagam is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# Metagam is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Metagam.  If not, see <http://www.gnu.org/licenses/>.

import mg
import os
import json
import sys
from mg.constructor.processes import ConstructorInstance

def main():
    inst = ConstructorInstance("conf_get", "metagam")
    # parse cmdline
    if len(inst.cmdline_args) != 2:
        print "usage: mg_conf_get <app> <config.key>"
        os._exit(1)
    app_tag = inst.cmdline_args[0]
    key = inst.cmdline_args[1]
    # perform actions
    app = inst.appfactory.get_by_tag(app_tag)
    val = app.config.get(key)
    print json.dumps(val, indent=4, sort_keys=True)
    sys.stdout.flush()
    os._exit(0)

mg.dispatch(main)
