#!/usr/bin/python2.6

# This file is a part of Metagam project.
#
# Metagam is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# Metagam is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Metagam.  If not, see <http://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-

import mg
import os
import json
import sys
from mg.constructor.processes import ConstructorInstance

def main():
    inst = ConstructorInstance("conf_del", "metagam")
    # parse cmdline
    if len(inst.cmdline_args) != 2:
        print "usage: mg_conf_del <app> <config.key>"
        os._exit(1)
    app_tag = inst.cmdline_args[0]
    key = inst.cmdline_args[1]
    # perform actions
    app = inst.appfactory.get_by_tag(app_tag)
    conf = app.config_updater()
    conf.delete(key)
    conf.store()

mg.dispatch(main)
