#!/usr/bin/python2.6
# -*- coding: utf-8 -*-

# This file is a part of Metagam project.
#
# Metagam is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# Metagam is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Metagam.  If not, see <http://www.gnu.org/licenses/>.

from mg import *
from concurrence import dispatch, quit
import os
import logging
import sys
import json
import re
import time

token_ring = 2 ** 127
parts = 256
token_part = token_ring / parts
re_app = re.compile('^(.+?)-(.+)$')

def main():
    try:
        if len(sys.argv) != 2:
            print "usage: mg_db_cleanup <app> or mg_db_cleanup all"
            os._exit(1)
        inst = Instance("db_cleanup")
        inst.download_config()
        mc = Memcached(inst.mcpool)
        db = inst.dbpool.dbget("main", mc)
        created = set()
        now = time.time() * 1000
        for family in ["Objects", "Indexes"]:
            for part in xrange(0, parts):
                start_token = '%d' % (part * token_part)
                end_token = '%d' % (((part + 1) * token_part) % token_ring)
                lst = db.get_range_slices(ColumnParent(family), SlicePredicate(slice_range=SliceRange("", "", False, 1000000000)), KeyRange(count=10000000, start_token=start_token, end_token=end_token), ConsistencyLevel.ONE)
                for ent in lst:
                    if len(ent.columns):
                        m = re_app.match(ent.key)
                        if m:
                            app, key = m.group(1, 2)
                            if app == sys.argv[1] or sys.argv[1] == "all":
                                print "removing %s/%s-%s" % (family, app, key)
                                db.remove(ent.key, ColumnPath(family), now, ConsistencyLevel.ONE)
        sys.stdout.flush()
        os._exit(0)
    except RuntimeError as e:
        logging.error(e)
        os._exit(1)
    except Exception as e:
        logging.exception(e)
        os._exit(1)

dispatch(main)

