#!/usr/bin/python2.6
# -*- coding: utf-8 -*-

# This file is a part of Metagam project.
#
# Metagam is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# Metagam is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Metagam.  If not, see <http://www.gnu.org/licenses/>.

from mg import *
from concurrence import dispatch, quit
import os
import logging
import sys
import json
import re
import time

token_ring = 2 ** 127

def main():
    try:
        inst = Instance("db_ring_check")
        inst.download_config()
        mc = Memcached(inst.mcpool)
        db = inst.dbpool.dbget("main", mc)
        created = set()
        ring = db.describe_ring("main")
        ring.sort(lambda x, y: cmp(int(x.start_token), int(y.start_token)))
        count = len(ring)
        for i in xrange(0, count):
            proper_token = token_ring / count * i
            actual_token = int(ring[i].start_token)
            if proper_token != actual_token:
                print "endpoint %s has token %d. change it to %d" % (ring[i].endpoints[0], actual_token, proper_token)
        sys.stdout.flush()
        os._exit(0)
    except RuntimeError as e:
        logging.error(e)
        os._exit(1)
    except Exception as e:
        logging.exception(e)
        os._exit(1)

dispatch(main)

