#!/usr/bin/python2.6
# -*- coding: utf-8 -*-

# This file is a part of Metagam project.
#
# Metagam is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# Metagam is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Metagam.  If not, see <http://www.gnu.org/licenses/>.

import mg
import os
import json
import sys
from mg.constructor.processes import ConstructorInstance

def main():
    inst = ConstructorInstance("enqueue", "metagam")
    # parse cmdline
    if len(inst.cmdline_args) != 3:
        print "usage: mg_enqueue <class> <app> <hook>"
        os._exit(1)
    app_cls = inst.cmdline_args[0]
    app_tag = inst.cmdline_args[1]
    hook = inst.cmdline_args[2]
    inst.int_app.load(["mg.core.queue.Queue"])
    inst.int_app.call("queue.add", hook, app_tag=app_tag, app_cls=app_cls)
    os._exit(0)

mg.dispatch(main)
