#!/bin/sh

# This file is a part of Metagam project.
#
# Metagam is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# Metagam is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Metagam.  If not, see <http://www.gnu.org/licenses/>.

bin/mg_conf_set $1 gameinterface.buttons-layout null
bin/mg_conf_set $1 gameinterface.panel-top true
bin/mg_conf_set $1 gameinterface.panel-main-left true
bin/mg_conf_set $1 gameinterface.panel-main-right false
bin/mg_conf_set $1 gameinterface.blocks-top null
bin/mg_conf_set $1 gameinterface.blocks-main-left null
bin/mg_conf_set $1 gameinterface.blocks-main-right null
bin/mg_conf_set $1 gameinterface.blocks-roster-buttons null
