#!/usr/bin/python2.6
# -*- coding: utf-8 -*-

# This file is a part of Metagam project.
#
# Metagam is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# Metagam is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Metagam.  If not, see <http://www.gnu.org/licenses/>.

from mg import *
from mg.core.queue import QueueTaskList
from concurrence import dispatch, quit
import os
import logging

def main():
    try:
        inst = Instance("dump")
        inst.download_config()
        int_app = WebApplication(inst, "int", "int")
        tasks = int_app.objlist(QueueTaskList, query_index="at")
        tasks.load(silent=True)
        for task in tasks:
            at = from_unixtime(task.get("at"))
            print "%s - %s.%s.%s - %s" % (at, task.get("cls"), task.get("app"), task.get("hook"), task.get("args"))
            if task.get("cls") == "main":
                task.set("cls", "metagam")
                task.store()
        quit(0)
    except RuntimeError as e:
        logging.error(e)
        os._exit(1)
    except Exception as e:
        logging.exception(e)
        os._exit(1)

dispatch(main)

