#!/usr/bin/python2.6

from concurrence import dispatch
import mg
import os
import optparse
import sys
import logging

def main():
    # configuration
    parser = optparse.OptionParser()
    (options, args) = parser.parse_args()
    # load everything
    inst = mg.Instance("reload", "metagam")
    app = inst.int_app
    app.load([
        "mg.core.cluster.Cluster",
    ])
    try:
        print "calling reload"    
    except RuntimeError as e:
        logging.error(e)
    except Exception as e:
        logging.exception(e)
    finally:
        os._exit(1)

dispatch(main)
