#!/usr/bin/python2.6

# This file is a part of Metagam project.
#
# Metagam is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# Metagam is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Metagam.  If not, see <http://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-

import mg
import os
import json
import sys
from mg.constructor.processes import ConstructorInstance
from mg.constructor.reqauction import DBRequestList

def main():
    inst = ConstructorInstance("reqauction_reset", "metagam")
    # parse cmdline
    if len(inst.cmdline_args) != 1:
        print "usage: mg_reqauction_reset <project>"
        os._exit(1)
    tag = inst.cmdline_args[0]
    app = inst.appfactory.get_by_tag(tag)
    lst = app.objlist(DBRequestList, query_index="all")
    lst.load(silent=True)
    for r in lst:
        r.set("category", "none")
        #r.delkey("parent")
    lst.store()
    sys.stdout.flush()
    os._exit(0)

mg.dispatch(main)
