#!/usr/bin/python2.6

from concurrence import dispatch
import mg
import os
import optparse
import sys
import logging

def main():
    # configuration
    parser = optparse.OptionParser()
    (options, args) = parser.parse_args()
    if not args:
        print "Usage: mg_reload <class>"
        os._exit(1)
    # load everything
    inst = mg.Instance("reload", args[0])
    app = inst.int_app
    app.load([
        "mg.core.cluster.Cluster",
    ])
    try:
        app.call("cluster.query-services", args[0], "/core/abort", call_int=True)
    except RuntimeError as e:
        logging.error(e)
    except Exception as e:
        logging.exception(e)
    finally:
        os._exit(1)

dispatch(main)
