#!/usr/bin/python2.6
# -*- coding: utf-8 -*-

from mg import *
from mg.core.classes import *
from concurrence import dispatch, quit
import os
import logging

def main():
    try:
        inst = Instance("dump")
        inst.download_config()
        int_app = WebApplication(inst, "int", "int")
        lst = int_app.objlist(WorkerStatusList, query_index="all")
        lst.load(silent=True)
        for st in lst:
            print "%s - %s" % (st.uuid, st.data)
        quit(0)
    except RuntimeError as e:
        logging.error(e)
        os._exit(1)
    except Exception as e:
        logging.exception(e)
        os._exit(1)

dispatch(main)

