#!/usr/bin/python2.6

# This file is a part of Metagam project.
#
# Metagam is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
# 
# Metagam is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Metagam.  If not, see <http://www.gnu.org/licenses/>.

# -*- coding: utf-8 -*-

import mg
import os
import json
import sys
from mg.constructor.processes import ConstructorInstance
from mg.core.money import DBXsollaActivationRequest, DBXsollaActivationRequestList
from mg.core.projects import ProjectList

def main():
    inst = ConstructorInstance("xsolla_activate", "metagam")
    lst = inst.int_app.objlist(ProjectList, query_index="created")
    for project in lst:
        app = inst.appfactory.get_by_tag(project.uuid)
        app.call("xsolla.check-activation")
    sys.stdout.flush()
    os._exit(0)

mg.dispatch(main)
